### ISSUE TITLE
Please add a License file too

### ISSUE THREAD

**Issue by prepare** [UglyToad/Pdf#1]
Which license type do you choose for your project?

Apache2 as original ?

---
Thank you

:)

**Comment by EliotJones** [comment]
I believe I will use Apache 2 but may also look at dual licencing to MIT if the Pdf Box team allow it.

For now there are quite a few more things to do before it even gets to alpha but it's safe to assume it will be Apache 2 licenced.

**Comment by EliotJones** [comment]
I've now added the license from the GitHub template. I may need to update this to include any required references to the licenses of PdfBox and FontBox but will do that when I'm much closer to the initial release. I will close this issue for now.
